/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_bme_mit_sette_snippets__10_native_dependencies_NativeObject */

#ifndef _Included_hu_bme_mit_sette_snippets__10_native_dependencies_NativeObject
#define _Included_hu_bme_mit_sette_snippets__10_native_dependencies_NativeObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_bme_mit_sette_snippets__10_native_dependencies_NativeObject
 * Method:    calculate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hu_bme_mit_sette_snippets__110_1native_dependencies_NativeObject_calculate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
