/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_bme_mit_sette_snippets__10_native_dependencies_NativeFunction */

#ifndef _Included_hu_bme_mit_sette_snippets__10_native_dependencies_NativeFunction
#define _Included_hu_bme_mit_sette_snippets__10_native_dependencies_NativeFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_bme_mit_sette_snippets__10_native_dependencies_NativeFunction
 * Method:    fun
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hu_bme_mit_sette_snippets__110_1native_dependencies_NativeFunction_fun
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
